# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BlDn4IBrhhMYrTKGDfmvIKzvuTW_bUJ_
"""

import numpy as np
import cv2
import matplotlib.pyplot as plt

img=np.zeros((100,500),dtype='uint8')
font=cv2.FONT_ITALIC
im=cv2.putText(img,' P. Siva Naga Nithin ',(5,70),font,1.5,(255),5,cv2.LINE_AA)
plt.imshow(cv2.cvtColor(im, cv2.COLOR_BAYER_GB2RGB))

Kernel=cv2.getStructuringElement(cv2.MORPH_CROSS,(11,11))

image1=cv2.morphologyEx(img,cv2.MORPH_OPEN,Kernel)
plt.imshow(cv2.cvtColor(image1,cv2.COLOR_BAYER_GB2RGB))

image1=cv2.morphologyEx(img,cv2.MORPH_CLOSE,Kernel)
plt.imshow(cv2.cvtColor(image1,cv2.cv2.COLOR_BAYER_GB2RGB))
plt.axis('off')